# Copyright 2022 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Paul Scheffler <paulsc@iis.ee.ethz.ch>

name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        target: [sw, hw, sim]
      fail-fast: false
    runs-on: windows-2025

    steps:
      - name: Setup WSL
        uses: vedantmgoyal9/setup-wsl2@main
        with:
          distro: Ubuntu

      - name: Set custom WSL mount root
        run: |
          wsl bash -c "echo -e '[automount]\nroot = /' | sudo tee /etc/wsl.conf"
          wsl --shutdown
          Start-Sleep -Seconds 10

      - name: Install Bender
        run: |
          wsl bash -c "curl --proto '=https' --tlsv1.2 https://pulp-platform.github.io/bender/init -sSf | sh"
          wsl bash -c 'ls -la /d/a/cheshire/cheshire/bender'

      - name: Install RISC-V GCC toolchain
        run: |
          wsl bash -c "set -e && curl -L https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2023.03.14/riscv64-elf-ubuntu-22.04-nightly-2023.03.14-nightly.tar.gz -o toolchain.tar.gz && mkdir -p ~/riscv && tar -xzf toolchain.tar.gz -C ~/riscv --strip-components=1"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Python
        run: |
          wsl bash -c "set -e; sudo apt update; for i in {1..5}; do sudo apt install -y python3 python3-pip python3-venv && break; echo 'APT failed, retrying (\$i)...'; sleep 10; done"

      - name: Install Python requirements
        run: wsl pip3 install -r requirements.txt

      - name: Build target
        run: |
          wsl bash -c 'export CHS_SW_GCC_BINROOT=~/riscv/bin BENDER=/d/a/cheshire/cheshire/bender && make ${{ matrix.target }}-all'

      - name: Check whether clean
        run: |
          wsl git status
          wsl test -z \"\$(git status --porcelain --ignore-submodules)\"
